[package]
name = "embedding_service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
rust-bert = "0.20.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
typenum = "1.16.0"
